### ISSUE TITLE
not working with kirby 4.0.0-rc.1

### ISSUE THREAD

**Issue by movingwater** [tobimori/kirby-icon-field#11]
Since the latest kirby version I cannot pick an icon. with the beta-2 of kirby it worked fine.
If an icon is already selected and I want to delete it, the following error shows in the console:
`index.min.js:1 TypeError: Cannot read properties of undefined (reading 'move')`

And there are also a lot of deprecated warnings:
```
index.min.js:1 Problem with plugin trying to register component "k-icon-selector-dropdown": cannot extend non-existent component "k-selector-dropdown"
index.min.js:1 Problem with plugin trying to register component "k-icon-selector": cannot extend non-existent component "k-selector"
```

**Comment by tobimori** [comment]
Known issue, the multi-select UI was unexpectedly completely overhauled in rc.1. Please stay on beta.2 for now If you want to use the plugin.

**Comment by nilshoerrmann** [comment]
Do you by any chance have a time frame for a Kirby 4 compatible release? Thanks :)

**Comment by tobimori** [comment]
I'm currently moving to Hamburg hence I have limited availability. Sorry for the inconvenience.

**Comment by nilshoerrmann** [comment]
No worries and thanks for the feedback!

**Comment by tobimori** [comment]
Hi, I just released a new version that should work with the new Picklist Input. Thanks for your patience!
