### ISSUE TITLE
Colored icons preview in field

### ISSUE THREAD

**Issue by alkachur** [tobimori/kirby-icon-field#15]
Hi there, when I try to implement coloured icons, in the field preview I see only the background of these icons.
Is there any ability to make them viewable because right now I can orient only with the icon name
<img width="443" alt="color-icons" src="https://github.com/tobimori/kirby-icon-field/assets/5717544/c7cb67ae-9c76-4ce9-a104-ddc12bf532ca">

**Comment by tobimori** [comment]
You can add custom CSS to your panel: https://getkirby.com/docs/quicktips/customizing-panel

**Comment by alkachur** [comment]
I think this isn't helps me. my icons looks like this
<img width="181" alt="color-icons2" src="https://github.com/tobimori/kirby-icon-field/assets/5717544/685bda8d-90e4-44fd-99a9-b2c505be0a14">

and in preview list in panel changing of color didn't help to understand what this icon is about only based on it's background

**Comment by tobimori** [comment]
You can remove the filter that makes it white using custom css.
