### ISSUE TITLE
Don't save "icon.svg" in a custom block

### ISSUE THREAD

**Issue by jp-clerc** [tobimori/kirby-icon-field#17]
I followed this [tutorial](https://getkirby.com/docs/reference/plugins/extensions/blocks#full-block-plugins__adding-a-default-blueprint-and-snippet) to create a custom icon block with other field like "size" and "decoration".
But once I press "Save" and "Reload" the field is not updated with the "icon.svg" :
`Testblock: [{"content":{"icone":"","style":"sans","size":"lg"},"isHidden":false,"type":"icons"}]`

On the other hand, outside a layout ou blocks field, it works perfectly.

**Comment by tobimori** [comment]
I'm currently using the plugin inside of a custom block and don't have any issues with the field. In any case, the demo block from the tutorial you provided works fine to me as well.

**Comment by jp-clerc** [comment]
Ah yes, it works with my dev server:
`"kirby": "4.3.0", "php": "8.1.28", "server": "Apache"`
but not with my local server:
`"kirby": "4.3.0", "php": "8.2.12","server": "Apache/2.4.58 (Win64) OpenSSL/3.1.3 PHP/8.2.12".`
This must be because of that.

Additional question: how long does it take to refresh the cache when enable? When I upload a new icon in the folder, with the panel, I don't see it instantly.

**Comment by tobimori** [comment]
The cache is never refreshed automatically, you have to delete it manually.

**Comment by jp-clerc** [comment]
Thanks a lot!
