### ISSUE TITLE
Allow Kirby query language in folder and sprite options

### ISSUE THREAD

**Issue by jan-herman** [tobimori/kirby-icon-field#19]
Hello again.
When I was messing around with #18, I realized that it might be useful to be able to use Kirby's query language in the field options. 

It should be pretty easy to implement. 

```php
// Folder option
'folder' => function ($folder = null) {
	if (!$folder) {
		$folder = option('tobimori.icon-field.folder', realpath(kirby()->roots()->index() . '/assets/icons'));
	}

        // Add Kirby query language support
	$folder = Str::template($folder, [
		'kirby' => ($kirby = kirby()),
		'site' => ($site = $kirby->site()),
		'page' => $site->page(),
	]);

	if (is_callable($folder)) {
		$folder = $folder($this);
	}

	if (!Str::startsWith($folder, '/')) {
		$folder = realpath(kirby()->roots()->index() . '/' . $folder);
	}

	return $folder;
},

// ...same thing in the sprite option
```

This would open up new possibilities, such as being able to define different sets of icons in the page model, or simply using different sprites based on the page template.

**Comment by tobimori** [comment]
can you make a PR with the changes? thanks

**Comment by jan-herman** [comment]
> can you make a PR with the changes? thanks

Done. #20
