### ISSUE TITLE
icon-field value is empty in frontend, when used in a block

### ISSUE THREAD

**Issue by Khepri-Design** [tobimori/kirby-icon-field#9]
kirby v4 beta2
kirby icon-field 2.0.0-rc.3

**Comment by tobimori** [comment]
This will be dealt with after the v4-rc.1 release.

**Comment by chrfickinger** [comment]
It's not only when used in a block. I have the same behavior on the blueprint of a page.

**Comment by tobimori** [comment]
> It's not only when used in a block. I have the same behavior on the blueprint of a page.

Your issue is unrelated to this.

**Comment by tobimori** [comment]
Hi @Khepri-Design - could you test this again with v2.0.0-rc.4? Thanks!

**Comment by Khepri-Design** [comment]
@tobimori works fine in Kirby 4.0.1
